"""Migracion

Revision ID: 56f1833431ea
Revises: c198362f2bbd
Create Date: 2026-02-26 20:45:17.184795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56f1833431ea'
down_revision = 'c198362f2bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=50), nullable=True))
        batch_op.drop_column('aMaterno')
        batch_op.drop_column('aPaterno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aPaterno', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('aMaterno', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
